# Generated by Django 3.0.5 on 2020-05-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('text', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('img', models.ImageField(upload_to='app_1/images/')),
            ],
        ),
    ]
