# Generated by Django 3.0.5 on 2020-05-13 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='img',
            old_name='age',
            new_name='many',
        ),
        migrations.AlterField(
            model_name='img',
            name='text',
            field=models.TextField(max_length=100),
        ),
    ]
