# Generated by Django 4.0.6 on 2022-07-22 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='note',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='sales',
            name='cost',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test2.item'),
        ),
    ]
