# Generated by Django 4.0.6 on 2022-07-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0002_alter_item_note_alter_sales_cost_alter_sales_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='note',
            field=models.TextField(default=' ', null=True),
        ),
    ]
